---
apiVersion: v1
kind: Service
metadata:
  name: authorization
  namespace: working-time-measurement
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8083
  selector:
    app: authorization
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: working-time-measurement
spec:
  selector:
    matchLabels:
      app: authorization
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - image: authorization
          name: authorization
          imagePullPolicy: Never
          env:
            - name: BASE_USER_NAME
              value: admin
            - name: BASE_USER_PASSWORD
              value: admin
---