---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-time
  namespace: working-time-measurement
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: user-password
    - name: user
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: user
      roles:
        - name: readWrite
          db: TimeEntries
        - name: readWrite
          db: VacationEntries
      scramCredentialsSecretName: user
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---