---
apiVersion: v1
kind: Secret
metadata:
  namespace: working-time-measurement
  name: user  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
type: Opaque
stringData:
  password: password