apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: working-time-measurement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wtm-frontend
  template:
    metadata:
      labels:
        app: wtm-frontend
    spec:
      containers:
        - name: wtm-frontend
          #image: docker.io/mika2147/wtm-frontend
          image: wtm-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env: 
            - name: REACT_APP_AUTHORIZATION_URL
              value: http://localhost/authorizationservice
              #value: http://4.182.3.55/authorizationservice
            - name: REACT_APP_TIME_URL
              value: http://localhost/timeservice
              #value: http://4.182.3.55/timeservice
            - name: REACT_APP_VACATION_URL
              value: http://localhost/vacationservice
              #value: http://4.182.3.55/vacationservice
---
apiVersion: v1
kind: Service
metadata:
  name: wtm-frontend
  namespace: working-time-measurement
spec:
  type: NodePort
  selector:
    app: wtm-frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000