server:
  port: 8083
app:
  datasource:
    jdbc-url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${BASE_USER_NAME:postgres}
    password: ${BASE_USER_PASSWORD:password}
    pool-size: 30
spring:
  datasource:
    url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://localhost:5432/users}
    jdbc-url: jdbc:postgresql://localhost:5432/users
    platform: postgres
    username: ${BASE_USER_NAME:postgres}
    password: ${BASE_USER_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect